### ISSUE TITLE
Test neovim

### ISSUE THREAD

**Issue by niklaci** [ioi-2023/contestant-vm#14]
Baltazár please create a PR for it

**Comment by niklaci** [comment]
@baltitenger

**Comment by baltitenger** [comment]
I'm happy to test neovim, tough it would also be nice to provide a basic set of plugins to allow neovim to utilize clangd, much like kate does. I suggest using the config shown in https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion.

(FWIW it's possible to have rudimentary LSP support with a few lines of lua shown in nvim help: https://neovim.io/doc/user/lsp.html#lsp-quickstart)

**Comment by radl97** [comment]
I think this is low prio.

However, I am not familiar with the ecosystem, and also focusing on finishing up a release. If you can create a PR which
- autoinstalls in setup.sh (hence, no GUI yet)
- does not work unexpectedly for folks who use vanilla neovim
- or alternatively for the above: present two launch options, one vanilla neovim, one with the favourite plugin installed.
then I think this would be safe to merge.

Note that if some additional plugins need to be installed, we should consider *not* adding this too (e.g. the size of a larger JS engine). The image size is not only a usability issue (constraint on tester's machine with published VM), but a performance issue: (re)imaging must be done mass-scale before contests or in the event of large-scale issues during contests.

**Comment by radl97** [comment]
Note that `neovim` is installed now, and we should test whether it works well. The above comment is only about adding LSP plugin.

Testing `neovim` should be the priority now, before anything.

**Comment by radl97** [comment]
I've tested that it works. I do not know the feature set of nvim, so I've just it as a plain vim, and it works. That is enough for now, I think
