### ISSUE TITLE
Launching of icons is not allowed

### ISSUE THREAD

**Issue by horcsinbalint** [ioi-2023/contestant-vm#27]
When I click on gnome-desktop-panel.desktop, it gives an error:
![image](https://github.com/ioi-2023/contestant-vm/assets/51171286/d91c3b3b-266a-421b-b4d6-75bdbf519bff)

**Comment by horcsinbalint** [comment]
Should probably add in the install script:
```sh
gio set /home/ioi/Desktop/gnome-keyboard-panel.desktop metadata::trusted true
```

**Comment by radl97** [comment]
It is there, in theory :/

**Comment by radl97** [comment]
Thanks for the investigation!

![image](https://github.com/ioi-2023/contestant-vm/assets/7879888/7bc203c4-bac0-4a01-91f2-3d069766d1e4)

So `gsettings` is allowed, but `gio` is not for DBus at the point when the script is executed.

**Comment by horcsinbalint** [comment]
I also wonder, if there is a problem with not having the full path here:
```shell
sudo -Hu ioi dbus-run-session gio set /home/ioi/Desktop/gnome-keyboard-panel.desktop metadata::trusted true
```
sbin/mkioiuser.sh:28

**Comment by radl97** [comment]
Oh, my...

**Comment by horcsinbalint** [comment]
Did this fix the issue. I think it is only one of our issues

**Comment by horcsinbalint** [comment]
Tested, it works
