### ISSUE TITLE
Neovim LSP

### ISSUE THREAD

**Issue by radl97** [ioi-2023/contestant-vm#32]
*[...] It would also be nice to provide a basic set of plugins to allow neovim to utilize clangd, much like kate does. I suggest using the config shown in https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion.*

*(FWIW it's possible to have rudimentary LSP support with a few lines of lua shown in nvim help: https://neovim.io/doc/user/lsp.html#lsp-quickstart)*

_Originally posted by @baltitenger in https://github.com/ioi-2023/contestant-vm/issues/14#issuecomment-1642495172_

**Comment by radl97** [comment]
I think this is low prio.

However, I am not familiar with the ecosystem, and also focusing on finishing up a release. If you can create a PR which

    autoinstalls in setup.sh (hence, no GUI yet)
    does not work unexpectedly for folks who use vanilla neovim
    or alternatively for the above: present two launch options, one vanilla neovim, one with the favourite plugin installed.
    then I think this would be safe to merge.

Note that if some additional plugins need to be installed, we should consider not adding this too (e.g. the size of a larger JS engine). The image size is not only a usability issue (constraint on tester's machine with published VM), but a performance issue: (re)imaging must be done mass-scale before contests or in the event of large-scale issues during contests.

**Comment by baltitenger** [comment]
Apparently in the latest versions of neovim it's possible to use LSP without any plugins at all with fairly little configuration. Since v0.9 the following is enough for completion, go-to-definition, and formatting support in c/c++:
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = {'c', 'cpp'},
  callback = function(ev)
    vim.lsp.start({
      name = 'clangd',
      cmd = {'clangd'},
    })
  end
})
```
There are a couple LSP features which don't have default keybindings, but setting them gets us the rest of the way.
```lua
vim.keymap.set('n', '<space>e', vim.diagnostic.open_float)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist)

vim.api.nvim_create_autocmd('LspAttach', {
  callback = function(ev)
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set({ 'n', 'v' }, '<space>ca', vim.lsp.buf.code_action, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>f', function()
      vim.lsp.buf.format { async = true }
    end, opts)
  end,
})
```
Of course, plugins are still required for autocompletion and snippet support.

Unfortunately, the current version in apt is quite outdated (v0.6.1) so I suggest installing the provided [AppImage](https://github.com/neovim/neovim/releases/download/stable/nvim.appimage) which is a single binary which needs to be placed in the PATH. (I suppose installing from snap could also work)

**Comment by radl97** [comment]
Choosing snap looks a promising option -- it's official Canonical stuff. AppImage is great, but we might run into untested configuration sets, hence bugs would be more common.

**Comment by baltitenger** [comment]
Should I open a pr for switching to the snap version of neovim?

**Comment by radl97** [comment]
Yes, please do! If you have the time, I would appreciate it. Also, if you can run a preliminary test on the PR, that would really help. I see you have a great setup for testing out different stuff -- in contrast, my tests are from the bottom-up, so as to be really sure what the contestant would see, but it's considerably slower.

**Comment by radl97** [comment]
Sorry for not getting back on to the issue, I am doing work in bursts, and I am doing my best to manage my time :D However, I see this as low priority currently, so a tested change is always a big help.
