### ISSUE TITLE
Passwords and Keys crash

### ISSUE THREAD

**Issue by horcsinbalint** [ioi-2023/contestant-vm#46]
![image](https://github.com/ioi-2023/contestant-vm/assets/51171286/6b5d7c59-3780-4031-a494-1a5a7596449d)
![image](https://github.com/ioi-2023/contestant-vm/assets/51171286/7cc9f099-2295-48c4-948a-f1bbb194b516)
![image](https://github.com/ioi-2023/contestant-vm/assets/51171286/8e31a3dd-629b-427a-933c-f5668ef59327)

**Comment by radl97** [comment]
Sometimes it happens... Dunno what to do with it. Duplicated #37
