### ISSUE TITLE
Suggestion: utils for terminal-based workflows

### ISSUE THREAD

**Issue by baltitenger** [ioi-2023/contestant-vm#57]
In my experience, the following utilities are commonly used in terminal-based workflows:
- bear: generate compile_commands.json from simple build systems
- tree: nice way to display directory structure
- qalc: calculator
- perf: performance auditing tool

**Comment by radl97** [comment]
Thanks for the heads-up! I think all of these are nice-to-have.

- Calculator: IIRC `bc` is available as a CLI tool.
- `perf` from `linux-tools` is a handy tool, and is not interchangeable with any other tool. I would also vouch for making it available. (maybe this would have an impact on size)
- Regarding `bear` -> I think it would be useful only for 10+ file projects, based on the project outline. I do not get why it would be useful, but I do not know the project.
- `tree` -> not great, not terrible.

Adding 4-8 packages (see other issues) seems a lot for me. If we get relevant issues, we will consider these, but I think it just bloats the already-bloated setup script.

**Comment by radl97** [comment]
I'll close this for now. If there is demand from contestants, we can revisit this.
