### ISSUE TITLE
Intellij IDEA Keybindings extension for VSCode

### ISSUE THREAD

**Issue by skittles1412** [ioi-2023/contestant-vm#60]
Hi,

Would it be possible to include the VSCode extension [Intellij IDEA Keybindings](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings) in the IOI VM? Given that CLion isn't supported, this extension would be very helpful to CLion users like myself who are planning to use VSCode at the IOI.

HSC last year rejected this proposal and said that it was impossible to have an extension installed in VSCode but disabled by default programmatically (they linked [this](https://github.com/microsoft/vscode/issues/52639) and [this](https://github.com/microsoft/vscode/issues/40239)).

I'm not sure if the situation has changed over the past year, but I think it's possible to work around this issue by providing the VSIX file as part of the VM image and have contestants install the VSIX manually if they wish to use the extension. It seems like vscodevim is currently getting this treatment (#58).

I'd greatly appreciate it if the extension could be included in the VM. For convenience, I believe the VSIX file for the current latest version of the extension can be downloaded at https://marketplace.visualstudio.com/_apis/public/gallery/publishers/k--kato/vsextensions/intellij-idea-keybindings/1.5.9/vspackage

Thanks!

**Comment by radl97** [comment]
Hi! Thanks for the detailed report.

This seems feasible on a technical perspective. @lacitoo what do you think?

---

Also, thank you for the links, I'll update the issue on VSCodeVim with the details you have provided.

> It seems like vscodevim is currently getting this treatment (https://github.com/ioi-2023/contestant-vm/issues/58).

Well, more like `vscodevim` as currently stuck at this point :D

**Comment by niklaci** [comment]
Yes, I think we can do it as suggested.

**Comment by horcsinbalint** [comment]
I got an error: `Corrupt ZIP: end of central directory record signature not found`
I was trying out 15f48f03c871068b10d17afa81717562971593d8

**Comment by horcsinbalint** [comment]
Sorry, when I try to install the VSIX in VS Code, I get the aforementioned error.

**Comment by radl97** [comment]
Thanks for checking it out!

> I'd greatly appreciate it if the extension could be included in the VM. For convenience, I believe the VSIX file for the current latest version of the extension can be downloaded at https://marketplace.visualstudio.com/_apis/public/gallery/publishers/k--kato/vsextensions/intellij-idea-keybindings/1.5.9/vspackage

This link is not the best. I think it's not provided as a public API. I am getting rate-limited after ~3 requests. I'll try from GitHub releases.

```
$ file intellij-idea-keybindings-1.5.9.vsix vim-1.25.2.vsix from-marketplace.vsix 
intellij-idea-keybindings-1.5.9.vsix: Zip archive data, at least v2.0 to extract
vim-1.25.2.vsix:                      Zip archive data, at least v2.0 to extract
from-marketplace.vsix:     gzip compressed data, max speed, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 442456
```

**Comment by radl97** [comment]
I got this

**Comment by radl97** [comment]
Thanks for bringing this to my attention!

Sorry for breaking `master`. I've fixed it. Ran a quick test to make sure. Please do test it again, just to make sure.

**Comment by horcsinbalint** [comment]
Thanks, it seems that it has fixed the issue.
