### ISSUE TITLE
Consider removing stl-manual

### ISSUE THREAD

**Issue by pobrn** [ioi-2023/contestant-vm#7]
It is old, pre-C++11. I don't quite see the point of having it when there is already a copy of cppreference available.

**Comment by radl97** [comment]
> C++-STL documentation in HTML. This is the documentation for the C++ Standard Template Library as found on SGIs Website.

It really is pretty old stuff: http://www.stlport.org/doc/sgi_stl.html

**Comment by horcsinbalint** [comment]
I'm reopening this, so we will not forget that the web page (https://ioi2023.hu/contest-environment/) also needs to be updated.

**Comment by radl97** [comment]
Already solved?

**Comment by horcsinbalint** [comment]
Yes, it's already solved, but we must remember to remove it from the webpage as well

**Comment by radl97** [comment]
Yes, it is already solved. You have attached a screenshot at #34 , where you can see the webpage is already updated.

**Comment by horcsinbalint** [comment]
Sorry, I meant https://ioi2023.hu/contest-environment/
