### ISSUE TITLE
Geany Plugins

### ISSUE THREAD

**Issue by Ghaffar06** [ioi-2023/contestant-vm#75]
Hi,

Would it be possible to include Geany plugins (https://plugins.geany.org/geany-plugins/geany-plugins-1.38.tar.gz)?

**Comment by radl97** [comment]
> Install via: `sudo apt-get install geany-plugins`
>
> or `sudo apt-get install geany-plugin-{pluginname}`

from the webpage. Would that be okay? (there are usually features missing from ubuntu distro packages, but it should be more stable and easier to integrate with the VM)

Also, which plugins would be used in particular? If there are only 3-4 of them, maybe we would consider listing them out (from a quick glance, we do not need sendmail)

Also, do I understand well, that the plugins are exactly the plugins and third party libraries listed on the sidebar here: https://plugins.geany.org/install.html ?

**Comment by Ghaffar06** [comment]
Hi,

> 
> `sudo apt-get install geany-plugins`
> or
> `sudo apt install geany-plugins`
> are okay, thanks!

And here is a list of the used plugins _(names as how they appear inside Geany)_:

- Auto-mark
- Line Operations
- Overview
- Save Actions
- Split Window
