### ISSUE TITLE
HIGH PRI: Can't change the Visual Studio Code Settings

### ISSUE THREAD

**Issue by boasbakker** [ioi-2023/contestant-vm#78]
**Describe the bug**
When trying to change the settings for Visual Studio Code, a blank screen appears without any settings.

**To Reproduce**
1. Open Visual Studio Code
2. Click on gear icon in the bottom left of the screen
3. Click on settings (Cntr+Comma)
4. See the blank screen

**Expected behavior**
A screen with various settings related to Visual Studio Code and C++ should appear, as was the case with the previous version of the VM.

**Screenshots**
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/0ee63f4a-b445-4405-be9c-bb4345de9cd3)

**Please complete the following information:**
 - For pre-built, image release version: contestant-vm-0804.ova

**Additional context**
-

**Comment by radl97** [comment]
It worked for me like this:
1. Open Visual Studio Code
2. In the menu, select "Open folder"
3. Select a new directory: In the directory selector, "Create new folder" icon on the top right corner, and name it "asd"
4. "Open" button
5. Create and save a new file called "asd.cpp"
6. Click on settings (Cntr+Comma)
7. The screen works as expected.

I think the most important step is to open a new folder. I guess user-related settings could be expected to show, but as there is no active workspace, VSCode might be confused.

**Comment by horcsinbalint** [comment]
@boasbakker thank you for reporting the issue.

I have been able to reproduce the issue. Steps:
- create a new VM
- do IOI setup
- open VS Code, and do the following:
  - open the Documents folder
  - trust its authors
  - open an integrated terminal
  - try to open settings
 
I do not know whether any of these steps is redundant.
I have also tested natively on one of the contestant machines, and was capable of producing the issue with the same steps (except for creating a new VM, I did the setup and cleanup from the repo). Here is a video about the bug:
https://youtu.be/9lkSG8uNiEI?t=75

I believe it is quite possible that these steps will be taken by contestants in the real competition. I think this bug has **high priority**.
@radl97 do you have any idea what could potentially cause this bug to happen? I have not seen any issues relating to this on the VS Code github.

**Comment by radl97** [comment]
Can you check
- `netstat -pt` for open TCP connections which may be relevant? It should be a row SYN_SENT. (`grep SYN_SENT`)
- Whether the issue lingers for 30 seconds or 2 minutes or more?

**Comment by horcsinbalint** [comment]
I have sent it in PM

**Comment by boasbakker** [comment]
Can you make a new release of the VM with this issue fixed?

**Comment by radl97** [comment]
Hi! We are not actively developing the VM version at this point, as close to the contest as we are. Thank you for your understanding.

One ugly workaround I can think of off top top of my head is to shut down the network of the VM. You van do this through VM management (in the status bar, bottom right) OR in the VM's user interface (top right). Start VSCode like this, and open the options there.

On another note (another workaround), if you wait 2 minutes (for the TCP timeout), the menu does appear correctly.

**Comment by boasbakker** [comment]
Thank you, that works
