### ISSUE TITLE
Kate, kdevelop missing

### ISSUE THREAD

**Issue by radl97** [ioi-2023/contestant-vm#9]

**Comment by baltitenger** [comment]
Note: kate needs a language server for completion, so `clangd` should also be installed.

**Comment by baltitenger** [comment]
This might be an apt bug or something...
From `/var/log/apt/history.txt`:
```
Commandline: apt -y remove llvm-13-dev zlib1g-dev libobjc-11-dev libx11-dev dpkg-dev manpages-dev
Requested-By: ansible (1000)
Install: libqt5gui5-gles:amd64 (5.15.3+dfsg-1, automatic), libqt5quick5-gles:amd64 (5.15.3+dfsg-1, automatic)
Remove: manpages-dev:amd64 (5.10-1ubuntu1), libglu1-mesa-dev:amd64 (9.0.2-1), libglx-dev:amd64 (1.4.0-1), libegl-dev:amd64 (1.4.0-1), build-essential:amd64 (12.9ubuntu3), qml-module-org-kde-kquickcontrols:amd64 (5.92.0-0ubuntu1), kaccounts-providers:amd64 (4:21.12.3-0ubuntu1), libpython3-dev:amd64 (3.10.6-1~22.04), qtscript5-dev:amd64 (5.15.3+dfsg-1), qml-module-org-kde-kirigami2:amd64 (5.92.0-0ubuntu2), kate:amd64 (4:21.12.3-0ubuntu1), kdeconnect:amd64 (21.12.3-0ubuntu1), llvm-13-dev:amd64 (1:13.0.1-2ubuntu2.1), libkf5coreaddons-dev:amd64 (5.92.0-0ubuntu1), libkf5config-dev:amd64 (5.92.0-0ubuntu1), libkf5i18n-dev:amd64 (5.92.0-0ubuntu2), zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu9.2), kdevelop:amd64 (4:21.12.3-0ubuntu1), qml-module-ubuntu-onlineaccounts:amd64 (0.6+17.04.20170405-0ubuntu5), libqt5quick5:amd64 (5.15.3+dfsg-1), qml-module-org-kde-qqc2desktopstyle:amd64 (5.92.0-0ubuntu1), libobjc-11-dev:amd64 (11.3.0-1ubuntu1~22.04.1), qml-module-qtmultimedia:amd64 (5.15.3-1), libqt5gui5:amd64 (5.15.3+dfsg-2ubuntu0.2), dpkg-dev:amd64 (1.21.1ubuntu2.2), qml-module-qtwebengine:amd64 (5.15.9+dfsg-1), qml-module-org-kde-purpose:amd64 (5.92.0-0ubuntu1), libqt5opengl5:amd64 (5.15.3+dfsg-2ubuntu0.2), qtbase5-dev:amd64 (5.15.3+dfsg-2ubuntu0.2), python3-dev:amd64 (3.10.6-1~22.04), libkf5service-dev:amd64 (5.92.0-0ubuntu1), qml-module-qtgraphicaleffects:amd64 (5.15.3-1), libkf5dbusaddons-dev:amd64 (5.92.0-0ubuntu1), libpython3.10-dev:amd64 (3.10.6-1~22.04.2ubuntu1.1), clang-13:amd64 (1:13.0.1-2ubuntu2.1), libx11-dev:amd64 (2:1.7.5-1ubuntu0.2), libgl-dev:amd64 (1.4.0-1), libqt5opengl5-dev:amd64 (5.15.3+dfsg-2ubuntu0.2), qml-module-qtquick-privatewidgets:amd64 (5.15.3-1), python3.10-dev:amd64 (3.10.6-1~22.04.2ubuntu1.1), libxext-dev:amd64 (2:1.3.4-1build1), libxt-dev:amd64 (1:1.2.1-1), qml-module-qtquick-controls:amd64 (5.15.3-1), qml-module-org-kde-newstuff:amd64 (5.92.0-0ubuntu1.1), libkf5purpose-bin:amd64 (5.92.0-0ubuntu1), qml-module-qtquick2:amd64 (5.15.3+dfsg-1), qml-module-qtquick-dialogs:amd64 (5.15.3-1), plasma-framework:amd64 (5.92.0-0ubuntu1), libkf5windowsystem-dev:amd64 (5.92.0-0ubuntu1)
```

A workaround I found is installing `libqt5gui5-gles` and `libqt5quick5-gles` manually before this remove step.

**Comment by radl97** [comment]
My guess is that mixing install and remove commands might be the problem: some package is not yet marked explicit, it is deleted after, and installing some parts automatically reinstalls the library as an effect? Or something like this?

**Comment by radl97** [comment]
I would like to dig into the issue because this fix looks fragile; it would probably break later years (migrating 20->22.04 was a pain, I do not want to merge too many hacks)

**Comment by radl97** [comment]
Okay, I'll try to look into alternatives. I think we don't need to kill libx11-dev, for example

**Comment by baltitenger** [comment]
Yeah, that would also be a possible workaround but imo just as fragile.

**Comment by radl97** [comment]
fwiw I am against removing any package at all. That is the main issue basically

**Comment by radl97** [comment]
It messed up qemu support, native support, specific migration paths already. So I think the solution would be an additional comment that between releases, it would be useful to reiterate which packages would be needed.

Another idea: Maybe instead of removing, we should mark such packages not-explicitly-installed, so an apt autoremove removes only packages which are really unused by our system.

**Comment by radl97** [comment]
Package management is hard :'(

**Comment by baltitenger** [comment]
I agree, I didn't know apt installed "suggested" stuff by default. Turning it off and installing only what we need in the first place could be a solution but I'm afraid it might break some things we didn't know we were using...

**Comment by radl97** [comment]
Hmm... I don't know. I have assumed that Ubuntu 22.04 marks these as explicit as they are part of the minimal desktop package. (or they used to be at 20.04. I have not tried to update package removals at all)

The main idea is that `apt-mark auto` fully prevents breakage (there is no explicit `remove` which recursively destroys explicitly installed packages). The original path is fragile, unintuitive from our perspective, and thus, I think, should be avoided.

In practice, this might mean that we fail to uninstall some packages like this. I think the unused, but ones suggested by other packages fall into that category.

We could iterate through the package list, and sweep through them manually. The most important would be the packages marked as explicitly installed, and the ones not required for something explicitly installed (only *suggested*, not required), and find out if they are used, and how much space does it free if we remove it*.

As I have noted somewhere, image size is important. So it would be interesting to reach some conclusion.

*: note that there are interesting cases. Assume `some-ide` suggests `something-dev`, which requires a large package called `something`. If we remove `something-dev` and then `autoremove`, then `something` is also removed, hence more space is freed.
