### ISSUE TITLE
21583a0 broke the script

### ISSUE THREAD

**Issue by horcsinbalint** [ioi-2023/contestant-vm#92]
**Describe the bug**
After 21583a0, the script is no longer functional, fails during the cpp reference download

**To Reproduce**
Run the script

**Expected behavior**
The script successfully executes

**Please complete the following information:**

 - For manual build, commit: 21583a0
   - I have used autoinstall: no

**Additional context**
Made hotfix 7011d30 for [dd-copy-native](https://github.com/ioi-2023/contestant-vm/tree/dd-copy-native). The bug was probably introduced by #91. Adding new untested features this close to the deadline (this midnight) is not a great idea.

**Comment by radl97** [comment]
I am sorry :/

**Comment by horcsinbalint** [comment]
No problem, I created a PR now for fixing the issue
