### ISSUE TITLE
Ubuntu iso download url returns 404

### ISSUE THREAD

**Issue by pobrn** [ioi-2023/contestant-vm#93]
Ubuntu 22.04.3 was released (https://discourse.ubuntu.com/t/jammy-jellyfish-22-04-3-lts-point-release-status-tracking/37439) a couple days ago, and as a consequence https://www.releases.ubuntu.com/22.04/ubuntu-22.04.2-live-server-amd64.iso returns 404.

**Comment by radl97** [comment]
`F.*`

**Comment by radl97** [comment]
The ISO moved to https://old-releases.ubuntu.com/releases/jammy/

**Comment by radl97** [comment]
I would prefer keeping 22.04.2 this close to the deadline. I am sad that that the stable release is always available in a different way than an old release...
